package com.resqhub.model;

import java.time.LocalDateTime;

/**
 * A single alert / notification delivered to a user account.
 *
 * Each notification targets a recipient (user account), carries a
 * type + priority + status, and optionally links back to the module
 * and event that produced it (e.g. the rescue request that triggered
 * a CRITICAL alert) so users can trace the source.
 *
 * The {@code dedupKey} + {@code autoGenerated} pair drive automatic
 * alert generation: the system records how each alert was produced so
 * it can avoid flooding users with hundreds of identical alerts.
 */
public class Notification extends BaseEntity {

    private Long recipientUserId;
    private NotificationType type = NotificationType.SYSTEM;
    private NotificationPriority priority = NotificationPriority.INFO;
    private NotificationStatus status = NotificationStatus.UNREAD;
    private String message;
    private String relatedModule;
    private Long relatedEventId;
    private boolean autoGenerated;
    private String dedupKey;
    private LocalDateTime readAt;

    public Notification() {
        super();
    }

    @Override
    public String getDetails() {
        String statusLabel = status == null ? "?" : status.getLabel();
        return "[" + (priority == null ? "?" : priority.getLabel())
                + "] " + (type == null ? "?" : type.getLabel())
                + " (" + statusLabel + "): "
                + (message == null ? "" : message);
    }

    public Long getRecipientUserId() {
        return recipientUserId;
    }

    public void setRecipientUserId(Long recipientUserId) {
        this.recipientUserId = recipientUserId;
    }

    public NotificationType getType() {
        return type;
    }

    public void setType(NotificationType type) {
        this.type = type;
    }

    public NotificationPriority getPriority() {
        return priority;
    }

    public void setPriority(NotificationPriority priority) {
        this.priority = priority;
    }

    public NotificationStatus getStatus() {
        return status;
    }

    public void setStatus(NotificationStatus status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getRelatedModule() {
        return relatedModule;
    }

    public void setRelatedModule(String relatedModule) {
        this.relatedModule = relatedModule;
    }

    public Long getRelatedEventId() {
        return relatedEventId;
    }

    public void setRelatedEventId(Long relatedEventId) {
        this.relatedEventId = relatedEventId;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getDedupKey() {
        return dedupKey;
    }

    public void setDedupKey(String dedupKey) {
        this.dedupKey = dedupKey;
    }

    public LocalDateTime getReadAt() {
        return readAt;
    }

    public void setReadAt(LocalDateTime readAt) {
        this.readAt = readAt;
    }
}
