package com.resqhub.service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.resqhub.dao.NotificationDAO;
import com.resqhub.dao.UserDAO;
import com.resqhub.dao.VolunteerDAO;
import com.resqhub.exception.DataAccessException;
import com.resqhub.exception.InvalidNotificationDataException;
import com.resqhub.exception.UnauthorizedOperationException;
import com.resqhub.model.Donation;
import com.resqhub.model.DonationStatus;
import com.resqhub.model.DonationType;
import com.resqhub.model.Notification;
import com.resqhub.model.NotificationPriority;
import com.resqhub.model.NotificationStatus;
import com.resqhub.model.NotificationType;
import com.resqhub.model.PriorityLevel;
import com.resqhub.model.RequestStatus;
import com.resqhub.model.RescueRequest;
import com.resqhub.model.RoleType;
import com.resqhub.model.Shelter;
import com.resqhub.model.User;
import com.resqhub.model.Volunteer;
import com.resqhub.util.ValidationUtil;

/**
 * Notification Center business logic.
 *
 * Centralises manual alert creation, role-based routing (broadcast to a
 * role), per-user viewing/mark-read/filter, and AUTOMATIC alert
 * generation driven by business rules:
 *
 *   IF rescue_priority = CRITICAL           -> CRITICAL_RESCUE alert
 *   IF remaining material stock <= threshold -> LOW_STOCK alert
 *   volunteer task / rescue team assigned   -> ASSIGNMENT notification
 *
 * Automatic alerts are scoped to data present in this codebase
 * (critical requests, donated-material stock, volunteer & team
 * assignments) and are de-duplicated so a condition that stays true
 * does not flood users with endless identical alerts (see
 * {@link #DEDUP_WINDOW_SECONDS}).
 */
public class NotificationService {

    /** Auto alerts are only re-issued once per key per window. */
    private static final long DEDUP_WINDOW_SECONDS = 6 * 60 * 60;

    /** Remaining donated units at or below this become a LOW_STOCK alert. */
    private static final int LOW_STOCK_THRESHOLD = 10;

    private final NotificationDAO notificationDAO = new NotificationDAO();
    private final UserDAO userDAO = new UserDAO();
    private final VolunteerDAO volunteerDAO = new VolunteerDAO();
    private final SessionManager session = SessionManager.getInstance();

    // ── manual creation ──────────────────────────────────────────────

    /**
     * Creates a notification for a specific recipient (any logged-in user
     * can post to themselves or, with elevation, to another account).
     */
    public Notification createNotification(Long recipientUserId,
            NotificationType type, NotificationPriority priority,
            String message, String relatedModule, Long relatedEventId)
            throws UnauthorizedOperationException,
            InvalidNotificationDataException, DataAccessException {

        session.requireRole();
        validate(type, priority, message);
        if (recipientUserId == null) {
            throw new InvalidNotificationDataException(
                    "a recipient is required");
        }

        Notification n = new Notification();
        n.setRecipientUserId(recipientUserId);
        n.setType(type);
        n.setPriority(priority);
        n.setStatus(NotificationStatus.UNREAD);
        n.setMessage(message.trim());
        n.setRelatedModule(relatedModule);
        n.setRelatedEventId(relatedEventId);
        n.setAutoGenerated(false);
        n.setDedupKey(null);
        return notificationDAO.save(n);
    }

    /** Broadcasts an alert to every active account of the given roles. */
    public int broadcast(NotificationType type, NotificationPriority priority,
            String message, String relatedModule, RoleType... roles)
            throws UnauthorizedOperationException,
            InvalidNotificationDataException, DataAccessException {

        session.requireRole(RoleType.ADMIN, RoleType.RESCUE_OFFICER);
        validate(type, priority, message);

        Set<Long> recipients = collectRecipients(roles);
        if (recipients.isEmpty()) {
            throw new InvalidNotificationDataException(
                    "no active accounts match the chosen audience");
        }
        for (Long userId : recipients) {
            createNotification(userId, type, priority,
                    message, relatedModule, null);
        }
        return recipients.size();
    }

    /** Recipient ids across the union of requested roles (or all users). */
    private Set<Long> collectRecipients(RoleType... roles)
            throws DataAccessException {
        Set<Long> ids = new LinkedHashSet<>();
        if (roles == null || roles.length == 0) {
            for (User user : userDAO.findAll()) {
                ids.add(user.getId());
            }
            return ids;
        }
        for (RoleType role : roles) {
            for (User user : userDAO.findByRole(role)) {
                ids.add(user.getId());
            }
        }
        return ids;
    }

    // ── viewing / status ─────────────────────────────────────────────

    /** All notifications addressed to the logged-in user. */
    public List<Notification> getMyNotifications()
            throws DataAccessException {
        Long userId = currentUserIdOrZero();
        return notificationDAO.findByRecipient(userId);
    }

    /** Filtered view (type / priority / status, each optional). */
    public List<Notification> filterMine(NotificationType type,
            NotificationPriority priority, NotificationStatus status)
            throws DataAccessException {
        Long userId = currentUserIdOrZero();
        return notificationDAO.findByRecipientFiltered(
                userId, type, priority, status);
    }

    public int countUnread() throws DataAccessException {
        return notificationDAO.countUnread(currentUserIdOrZero());
    }

    /** Marks one own notification as READ. */
    public void markRead(long notificationId)
            throws UnauthorizedOperationException, InvalidNotificationDataException,
            DataAccessException {
        requireOwn(notificationId);
        notificationDAO.markRead(notificationId);
    }

    /** Marks every unread notification of the current user as READ. */
    public void markAllRead() throws DataAccessException {
        notificationDAO.markAllRead(currentUserIdOrZero());
    }

    /** Archives one own notification (removes it from the active list). */
    public void archive(long notificationId)
            throws UnauthorizedOperationException, InvalidNotificationDataException,
            DataAccessException {
        requireOwn(notificationId);
        notificationDAO.archive(notificationId);
    }

    public Notification get(long id)
            throws InvalidNotificationDataException, DataAccessException {
        Notification n = notificationDAO.findById(id);
        if (n == null) {
            throw new InvalidNotificationDataException(
                    "No notification with id " + id);
        }
        return n;
    }

    // ── automatic alert generation ───────────────────────────────────

    /**
     * Runs the automatic business-rule checks and creates de-duplicated
     * alerts for the conditions that currently hold. Returns the number
     * of NEW alerts created. Safe to call repeatedly (e.g. on switching
     * to the module or on a refresh timer).
     */
    public int generateAutomaticAlerts()
            throws UnauthorizedOperationException, DataAccessException {
        session.requireRole(RoleType.ADMIN, RoleType.RESCUE_OFFICER,
                RoleType.CAMP_MANAGER);
        int created = 0;
        created += generateCriticalRescueAlerts();
        created += generateLowStockAlerts();
        created += generateShelterCapacityAlerts();
        return created;
    }

    /** IF rescue_priority = CRITICAL -> alert the operations staff. */
    private int generateCriticalRescueAlerts() throws DataAccessException {
        List<RescueRequest> critical = new RescueRequestService()
                .findCriticalOpen();
        if (critical.isEmpty()) {
            return 0;
        }
        List<User> staff = new ArrayList<>();
        staff.addAll(userDAO.findByRole(RoleType.ADMIN));
        staff.addAll(userDAO.findByRole(RoleType.RESCUE_OFFICER));
        if (staff.isEmpty()) {
            return 0;
        }

        int created = 0;
        Set<Long> seen = new LinkedHashSet<>();
        // If more than a handful of critical requests are open, alert once
        // with the summary instead of one alert per request (avoid flooding).
        if (critical.size() > 3) {
            String dedup = "CRITICAL_RESCUE:BATCH";
            if (notificationDAO.findRecentByDedupKey(
                    dedup, DEDUP_WINDOW_SECONDS) == null) {
                String message = critical.size()
                        + " CRITICAL rescue requests currently need immediate"
                        + " attention.";
                for (User user : staff) {
                    if (!seen.add(user.getId())) {
                        continue;
                    }
                    notificationDAO.save(buildAuto(
                            user.getId(), NotificationType.CRITICAL_RESCUE,
                            NotificationPriority.CRITICAL, message,
                            "Rescue Requests", null, dedup));
                    created++;
                }
            }
            return created;
        }

        for (RescueRequest request : critical) {
            String dedup = "CRITICAL_RESCUE:" + request.getId();
            if (notificationDAO.findRecentByDedupKey(
                    dedup, DEDUP_WINDOW_SECONDS) != null) {
                continue;
            }
            String message = "CRITICAL rescue request at "
                    + request.getLocation() + " - "
                    + request.getPeopleCount() + " people need rescue"
                    + (request.isMedicalEmergency() ? ", medical emergency" : "")
                    + ".";
            for (User user : staff) {
                if (!seen.add(user.getId())) {
                    continue;
                }
                notificationDAO.save(buildAuto(
                        user.getId(), NotificationType.CRITICAL_RESCUE,
                        NotificationPriority.CRITICAL, message,
                        "Rescue Requests", request.getId(), dedup));
                created++;
            }
        }
        return created;
    }

    /** IF remaining material stock <= threshold -> LOW_STOCK alert. */
    private int generateLowStockAlerts() throws DataAccessException {
        List<User> audience = new ArrayList<>();
        audience.addAll(userDAO.findByRole(RoleType.ADMIN));
        audience.addAll(userDAO.findByRole(RoleType.CAMP_MANAGER));
        if (audience.isEmpty()) {
            return 0;
        }
        Set<Long> seen = new LinkedHashSet<>();
        for (User user : audience) {
            seen.add(user.getId());
        }

        Map<String, Integer> remainingByMaterial = remainingMaterialStock();
        int created = 0;
        for (Map.Entry<String, Integer> entry
                : remainingByMaterial.entrySet()) {
            int remaining = entry.getValue();
            if (remaining > LOW_STOCK_THRESHOLD) {
                continue;
            }
            String dedup = "LOW_STOCK:" + entry.getKey();
            if (notificationDAO.findRecentByDedupKey(
                    dedup, DEDUP_WINDOW_SECONDS) != null) {
                continue;
            }
            String message = "Donated stock low: " + entry.getKey()
                    + " has only " + remaining
                    + " unit(s) remaining - request more supplies.";
            for (Long userId : seen) {
                notificationDAO.save(buildAuto(
                        userId, NotificationType.LOW_STOCK,
                        NotificationPriority.WARNING, message,
                        "Donations", null, dedup));
                created++;
            }
        }
        return created;
    }

    /** IF shelter occupancy >= 90% of capacity (and not already FULL /
     *  CLOSED) -> SHELTER NEARING CAPACITY warning to camp coordination. */
    private int generateShelterCapacityAlerts() throws DataAccessException {
        List<Shelter> near = new ShelterService().getNearCapacity();
        if (near.isEmpty()) {
            return 0;
        }
        List<User> audience = new ArrayList<>();
        audience.addAll(userDAO.findByRole(RoleType.ADMIN));
        audience.addAll(userDAO.findByRole(RoleType.RESCUE_OFFICER));
        audience.addAll(userDAO.findByRole(RoleType.CAMP_MANAGER));
        if (audience.isEmpty()) {
            return 0;
        }
        Set<Long> seen = new LinkedHashSet<>();
        for (User user : audience) {
            seen.add(user.getId());
        }

        int created = 0;
        for (Shelter shelter : near) {
            String dedup = "SHELTER_CAPACITY:" + shelter.getId();
            if (notificationDAO.findRecentByDedupKey(
                    dedup, DEDUP_WINDOW_SECONDS) != null) {
                continue;
            }
            String message = "SHELTER NEARING CAPACITY: " + shelter.getName()
                    + " has " + shelter.availableCapacity()
                    + " space(s) left out of " + shelter.getMaxCapacity()
                    + " (" + shelter.getCurrentOccupancy() + " occupied).";
            for (Long userId : seen) {
                notificationDAO.save(buildAuto(
                        userId, NotificationType.SYSTEM,
                        NotificationPriority.WARNING, message,
                        "Shelters", shelter.getId(), dedup));
                created++;
            }
        }
        return created;
    }

    /**
     * Aggregates remaining (undistributed) donated units per material
     * item across all material donations that are not fully distributed.
     */
    private Map<String, Integer> remainingMaterialStock()
            throws DataAccessException {
        Map<String, Integer> stock = new HashMap<>();
        DonationService donationService = new DonationService();
        for (Donation donation : donationService.getAllDonations()) {
            if (donation.getDonationType() != DonationType.MATERIAL
                    || donation.getStatus() == DonationStatus.DISTRIBUTED
                    || donation.getMaterialName() == null) {
                continue;
            }
            int total = donation.getQuantity() == null
                    ? 0 : donation.getQuantity();
            int distributed = donationService.sumDistributed(
                    donation.getId());
            int remaining = Math.max(0, total - distributed);
            stock.merge(donation.getMaterialName(), remaining, Integer::sum);
        }
        return stock;
    }

    private Notification buildAuto(Long recipientUserId,
            NotificationType type, NotificationPriority priority,
            String message, String module, Long eventId, String dedupKey) {
        Notification n = new Notification();
        n.setRecipientUserId(recipientUserId);
        n.setType(type);
        n.setPriority(priority);
        n.setStatus(NotificationStatus.UNREAD);
        n.setMessage(message);
        n.setRelatedModule(module);
        n.setRelatedEventId(eventId);
        n.setAutoGenerated(true);
        n.setDedupKey(dedupKey);
        return n;
    }

    // ── assignment hooks ─────────────────────────────────────────────

    /**
     * Routes an ASSIGNMENT notification to a volunteer's linked account
     * when a new task is assigned to them. Skips volunteers without a
     * linked auth account (they cannot log in to see alerts).
     */
    public void notifyVolunteerAssigned(long volunteerId, String taskName,
            String location, int priority)
            throws DataAccessException {
        Volunteer volunteer = volunteerDAO.findById(volunteerId);
        if (volunteer == null || volunteer.getUserId() == null) {
            return;
        }
        NotificationPriority level = priority >= 3
                ? NotificationPriority.WARNING : NotificationPriority.INFO;
        Notification n = buildAuto(volunteer.getUserId(),
                NotificationType.ASSIGNMENT, level,
                "New task assigned: " + taskName
                        + (location == null || location.isBlank()
                            ? "" : " at " + location),
                "Volunteers", volunteerId,
                "ASSIGNMENT:V:" + volunteerId + ":" + taskName);
        notificationDAO.save(n);
    }

    /**
     * Routes an ASSIGNMENT notification to operations staff when a rescue
     * team is dispatched to a request.
     */
    public void notifyTeamAssigned(long requestId, long teamId,
            String location, boolean critical)
            throws DataAccessException {
        List<User> staff = new ArrayList<>();
        staff.addAll(userDAO.findByRole(RoleType.ADMIN));
        staff.addAll(userDAO.findByRole(RoleType.RESCUE_OFFICER));
        Set<Long> seen = new LinkedHashSet<>();
        String message = "Rescue team #" + teamId + " assigned to request #"
                + requestId + (location == null || location.isBlank()
                        ? "" : " at " + location)
                + (critical ? " (CRITICAL)" : "") + ".";
        for (User user : staff) {
            if (!seen.add(user.getId())) {
                continue;
            }
            notificationDAO.save(buildAuto(user.getId(),
                    NotificationType.ASSIGNMENT,
                    critical ? NotificationPriority.CRITICAL
                             : NotificationPriority.INFO,
                    message, "Rescue Requests", requestId,
                    "ASSIGNMENT:T:" + requestId + ":" + teamId));
        }
    }

    // ── helpers ──────────────────────────────────────────────────────

    private void validate(NotificationType type,
            NotificationPriority priority, String message)
            throws InvalidNotificationDataException {
        if (type == null) {
            throw new InvalidNotificationDataException(
                    "a notification type must be selected");
        }
        if (priority == null) {
            throw new InvalidNotificationDataException(
                    "a priority must be selected");
        }
        if (!ValidationUtil.requireNonBlank(message)) {
            throw new InvalidNotificationDataException(
                    "notification message cannot be empty");
        }
    }

    private void requireOwn(long notificationId)
            throws UnauthorizedOperationException,
            InvalidNotificationDataException, DataAccessException {
        Notification n = notificationDAO.findById(notificationId);
        if (n == null) {
            throw new InvalidNotificationDataException(
                    "No notification with id " + notificationId);
        }
        if (!n.getRecipientUserId().equals(currentUserIdOrZero())) {
            throw new UnauthorizedOperationException(
                    "You can only manage your own notifications");
        }
    }

    private Long currentUserIdOrZero() {
        Long id = session.currentUserId();
        return id == null ? 0L : id;
    }

    /** Convenience for tests/UI: current timestamp helper. */
    public LocalDateTime now() {
        return LocalDateTime.now();
    }
}
