package com.resqhub.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import com.resqhub.exception.DataAccessException;
import com.resqhub.model.Notification;
import com.resqhub.model.NotificationPriority;
import com.resqhub.model.NotificationStatus;
import com.resqhub.model.NotificationType;

/**
 * JDBC data access for the notifications table.
 *
 * In addition to the standard repository CRUD it exposes the query
 * surface needed by the Notification Center: recipient-scoped listing
 * with priority/type/status filters, unread counts, mark-read / archive
 * transitions, and lookups used for automatic-alert de-duplication.
 */
public class NotificationDAO extends BaseDao
        implements Repository<Notification> {

    @Override
    public Notification save(Notification n) throws DataAccessException {
        if (n.getId() == null) {
            return insert(n);
        }
        return update(n);
    }

    private Notification insert(Notification n) throws DataAccessException {
        String sql = "INSERT INTO notifications (recipient_user_id, type, "
                + "priority, status, message, related_module, "
                + "related_event_id, auto_generated, dedup_key, read_at) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql,
                     Statement.RETURN_GENERATED_KEYS)) {

            ps.setLong(1, n.getRecipientUserId());
            ps.setString(2, enumOrNull(n.getType()));
            ps.setString(3, enumOrNull(n.getPriority()));
            ps.setString(4, enumOrNull(n.getStatus()));
            ps.setString(5, n.getMessage());
            ps.setString(6, n.getRelatedModule());
            bindNullableLong(ps, 7, n.getRelatedEventId());
            ps.setBoolean(8, n.isAutoGenerated());
            ps.setString(9, n.getDedupKey());
            if (n.getReadAt() == null) {
                ps.setNull(10, Types.TIMESTAMP);
            } else {
                ps.setObject(10, n.getReadAt());
            }
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    return findById(keys.getLong(1));
                }
            }
            throw new DataAccessException("No generated notification id");
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not save notification", e);
        }
    }

    private Notification update(Notification n) throws DataAccessException {
        String sql = "UPDATE notifications SET type = ?, priority = ?, "
                + "status = ?, message = ?, related_module = ?, "
                + "related_event_id = ?, auto_generated = ?, "
                + "dedup_key = ?, read_at = ? WHERE id = ?";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, enumOrNull(n.getType()));
            ps.setString(2, enumOrNull(n.getPriority()));
            ps.setString(3, enumOrNull(n.getStatus()));
            ps.setString(4, n.getMessage());
            ps.setString(5, n.getRelatedModule());
            bindNullableLong(ps, 6, n.getRelatedEventId());
            ps.setBoolean(7, n.isAutoGenerated());
            ps.setString(8, n.getDedupKey());
            if (n.getReadAt() == null) {
                ps.setNull(9, Types.TIMESTAMP);
            } else {
                ps.setObject(9, n.getReadAt());
            }
            ps.setLong(10, n.getId());
            int rows = ps.executeUpdate();
            if (rows != 1) {
                throw new DataAccessException(
                        "Notification update affected " + rows + " rows");
            }
            return findById(n.getId());
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not update notification", e);
        }
    }

    @Override
    public Notification findById(long id) throws DataAccessException {
        String sql = "SELECT * FROM notifications WHERE id = ?";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? mapRow(rs) : null;
            }
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not load notification " + id, e);
        }
    }

    @Override
    public List<Notification> findAll() throws DataAccessException {
        String sql = "SELECT * FROM notifications ORDER BY created_at DESC";
        List<Notification> result = new ArrayList<>();
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                result.add(mapRow(rs));
            }
            return result;
        } catch (SQLException e) {
            throw new DataAccessException("Could not list notifications", e);
        }
    }

    @Override
    public boolean deleteById(long id) throws DataAccessException {
        String sql = "DELETE FROM notifications WHERE id = ?";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, id);
            return ps.executeUpdate() == 1;
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not delete notification " + id, e);
        }
    }

    /** Every notification for one recipient, newest first. */
    public List<Notification> findByRecipient(long userId)
            throws DataAccessException {
        String sql = "SELECT * FROM notifications WHERE recipient_user_id = ? "
                + "ORDER BY created_at DESC";
        List<Notification> result = new ArrayList<>();
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    result.add(mapRow(rs));
                }
            }
            return result;
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not list notifications for user " + userId, e);
        }
    }

    /**
     * Recipient list with optional filters.
     * @param type null = all types
     * @param priority null = all priorities
     * @param status null = all statuses
     */
    public List<Notification> findByRecipientFiltered(long userId,
            NotificationType type, NotificationPriority priority,
            NotificationStatus status) throws DataAccessException {

        StringBuilder sql = new StringBuilder(
                "SELECT * FROM notifications WHERE recipient_user_id = ?");
        List<Object> params = new ArrayList<>();
        params.add(userId);
        if (type != null) {
            sql.append(" AND type = ?");
            params.add(type.name());
        }
        if (priority != null) {
            sql.append(" AND priority = ?");
            params.add(priority.name());
        }
        if (status != null) {
            sql.append(" AND status = ?");
            params.add(status.name());
        }
        sql.append(" ORDER BY created_at DESC");

        List<Notification> result = new ArrayList<>();
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql.toString())) {

            for (int i = 0; i < params.size(); i++) {
                if (params.get(i) instanceof Long) {
                    ps.setLong(i + 1, (Long) params.get(i));
                } else {
                    ps.setString(i + 1, (String) params.get(i));
                }
            }
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    result.add(mapRow(rs));
                }
            }
            return result;
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not filter notifications for user " + userId, e);
        }
    }

    public int countUnread(long userId) throws DataAccessException {
        String sql = "SELECT COUNT(*) FROM notifications "
                + "WHERE recipient_user_id = ? AND status = 'UNREAD'";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1);
            }
        } catch (SQLException e) {
            throw new DataAccessException("Count unread notifications failed", e);
        }
    }

    /** Marks a single notification as read (no-op if already read/archived). */
    public void markRead(long id) throws DataAccessException {
        String sql = "UPDATE notifications SET status = 'READ', "
                + "read_at = CURRENT_TIMESTAMP WHERE id = ? "
                + "AND status = 'UNREAD'";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not mark notification " + id + " as read", e);
        }
    }

    /** Marks a single notification as archived. */
    public void archive(long id) throws DataAccessException {
        String sql = "UPDATE notifications SET status = 'ARCHIVED' "
                + "WHERE id = ?";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not archive notification " + id, e);
        }
    }

    /** Marks every unread notification of a user as read. */
    public void markAllRead(long userId) throws DataAccessException {
        String sql = "UPDATE notifications SET status = 'READ', "
                + "read_at = CURRENT_TIMESTAMP "
                + "WHERE recipient_user_id = ? AND status = 'UNREAD'";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, userId);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Could not mark all notifications read", e);
        }
    }

    /**
     * Finds a recent auto-generated notification matching a dedup key,
     * so the scanner can avoid recreating an identical alert repeatedly.
     * Only UNREAD/READ (not archived) rows created within the lookback
     * window count toward de-duplication.
     */
    public Notification findRecentByDedupKey(String dedupKey, long lookbackSeconds)
            throws DataAccessException {
        String sql = "SELECT * FROM notifications WHERE dedup_key = ? "
                + "AND status <> 'ARCHIVED' "
                + "AND created_at >= (NOW() - INTERVAL ? SECOND) "
                + "ORDER BY created_at DESC LIMIT 1";
        try (Connection con = openConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, dedupKey);
            ps.setLong(2, lookbackSeconds);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? mapRow(rs) : null;
            }
        } catch (SQLException e) {
            throw new DataAccessException(
                    "Dedup lookup failed for " + dedupKey, e);
        }
    }

    private Notification mapRow(ResultSet rs) throws SQLException {
        Notification n = new Notification();
        n.setId(rs.getLong("id"));
        n.setRecipientUserId(rs.getLong("recipient_user_id"));
        n.setType(readEnum(NotificationType.class,
                rs.getString("type")));
        n.setPriority(readEnum(NotificationPriority.class,
                rs.getString("priority")));
        n.setStatus(readEnum(NotificationStatus.class,
                rs.getString("status")));
        n.setMessage(rs.getString("message"));
        n.setRelatedModule(rs.getString("related_module"));
        long eventId = rs.getLong("related_event_id");
        if (!rs.wasNull()) {
            n.setRelatedEventId(eventId);
        }
        n.setAutoGenerated(rs.getBoolean("auto_generated"));
        n.setDedupKey(rs.getString("dedup_key"));
        n.setReadAt(readLocalDateTime(rs, "read_at"));
        n.setCreatedAt(readLocalDateTime(rs, "created_at"));
        n.setUpdatedAt(readLocalDateTime(rs, "updated_at"));
        return n;
    }
}
